# Generated by Django 5.1.3 on 2024-11-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='submenucategory',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='SubMenuCategory',
        ),
    ]
